services:
  - type: web
    name: django-backend
    env: python
    plan: free
    branch: main  # or your GitHub branch name
    rootDir: Backend/user
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn user.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: user.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: DEBUG
        value: False
