# Generated by Django 5.1.1 on 2025-04-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
