# Generated by Django 5.1.1 on 2025-05-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_interests_customuser_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
